# Generated by Django 5.0.6 on 2024-07-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookstoreApp', '0002_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn10',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(max_length=17),
        ),
    ]
