services:
  kiiiapp:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    image: kiiiapp:latest
    container_name: kiii_project_container
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.app
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env.db
    container_name: kiii_db_container
volumes:
  db_data: